#Context Path
server.servlet.context-path: /erp

# yaml 프로퍼티를 사용하여 properties 설정하기
## classpath: spring src/main 폴더를 가리키는 키워드
spring:
  config.import: >
    optional:classpath: app-dbms.yml,
    classpath: app-logger.yml,
    classpath: app-data.yml
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-location: classpath:static/
      add-mappings: true


# DB connection setting
#  datasource:
#    driver-class-name: "com.mysql.cj.jdbc.Driver"
#    url: "jdbc:mysql://localhost:3306/naraDB"
#    username: root
#    password: "!Biz12341234"


#JPA Setting
  jpa:
    hibernate:
      ddl-auto: create

      jbc:
        batch_size: 100
      order_insert: true
      order_update: true

# option setting
    database: mysql
    database-plattform: "org.hibernate.dialect.MySQL8Dialect"
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  output.ansi.enabled: ALWAYS
