spring:
  config:
    import: >
      optional:classpath:application-jpa.yml,
      classpath:application-dbms.yml

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:static/
      add-mappings: true
  output:
    ansi:
      enabled: always